### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Mte90**
This pr fixes the issues with the provisioner as it is outdated

### CODE REVIEW

**Comment by Mte90** [comment]
It is not yet ready, ubuntu 18 doesn't have ruby 2.6 in their repository so this pr need to be updated.

**Comment by alessandro-fazzi** [comment]
One possible procedure to install ruby in a apt agnostic way

```
apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev git \
&& echo "gem: --no-document" > ~/.gemrc \
&& git clone https://github.com/rbenv/ruby-build.git ~/ruby-build \
&& PREFIX=/usr/local ~/ruby-build/install.sh \
&& RUBY_CONFIGURE_OPTS=--disable-install-doc ruby-build 2.6.6 /usr/local
```

Another way was suggested in https://github.com/welaika/wordmove/issues/598#issuecomment-619596936

```
snap install ruby --classic
```

I've not tested either in VVV: I'm just collecting suggestions if they could be someway useful

**Comment by Mte90** [comment]
Now it's finished and update with latest wordmove, ruby etc.
It's more simple and works :-)

**Comment by alessandro-fazzi** [comment]
I'm 105 faithful about your changes :) Go go go

**Pull request merged**
